# Análisis Multivariado de datos 1

En este cuaderno se presenta la implementación de algunas funciones, para calcular algunas de las estadísticas descriptivas básicas para datos muntivariados.

### *Nota: El código está escrito en R*


1) Matriz de dimensión $n\times p$ donde cada componente es igual a $1$.

In [1]:
ones <- function(n,p){
  return(matrix(rep(1,n*p), nrow=n, ncol=p))
}

#Ejemplo
print(ones(3,2))

     [,1] [,2]
[1,]    1    1
[2,]    1    1
[3,]    1    1


2. Matriz de $n\times p$ donde cada componente es igual a $0$.

In [2]:
zeros <- function(n,p){
    return( ones(n,p)*0 )
}

#Ejemplo 
print(zeros(3,2))

     [,1] [,2]
[1,]    0    0
[2,]    0    0
[3,]    0    0


3. Matriz identidad de tamaño $n \times n$. 

In [3]:
I <- function(n){
  A <- zeros(n,n)
  diag(A) <- ones(n,1)
  return(A)
}

#Ejemplo
print(I(3))

     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    1    0
[3,]    0    0    1


De ahora en adelante, tendremos como input a una matrix $X$, cuya entrada $x_{i,j}$ corresponderá a la medición de la variable $j$ sobre el individuo $i$.

4. Vector de medias.

In [4]:
mean_vec <- function(X){
    return(t(t(colMeans(X))))
}

#Ejemplo
print(mean_vec(cars))

       [,1]
speed 15.40
dist  42.98


5. Matriz de covarianzas muestrales, $S$. (Dividido entre (n-1))

In [5]:
#Ejemplo 
print(var(cars))

          speed     dist
speed  27.95918 109.9469
dist  109.94694 664.0608


6. Matriz de correlaciones muestrales ( $R = D^{-\frac{1}{2}} S D^{-\frac{1}{2}}$), con $D$ la matriz diagonal con los inversos de las desviaciones estándar sobre la diagonal)

In [6]:
#Ejemplo 
print(cor(cars))

          speed      dist
speed 1.0000000 0.8068949
dist  0.8068949 1.0000000


7. Varianza total ($tr(S)$)

In [7]:
var_tot <- function(X){
    return( sum(diag(var(X))) )
}

#Ejemplo
var_tot(cars)

[1] 692.02

In [8]:
var_gen <- function(X){
    return( det(var(X)) )
}

#Ejemplo
var_gen(cars)

[1] 6478.269